### ISSUE TITLE
Feature Request: Splitting Wide Tables into Two

### ISSUE THREAD

**Issue by JPGlaser** [odysseus9672/deluxetable.sty#1]
So I am currently working on my thesis document (which cannot use the aastex.cls document class structure), and would love to port in my deluxetables. They work just fine with this distribution, except I can't seem to get the tables to column split at the desired location. This feature is supported via using the 'B' argument in the column control array, but not recognized by this distro. Any ideas on how we can get this added in?

~ Joe G.

![image](https://user-images.githubusercontent.com/11276213/92760633-d7ba2f00-f35e-11ea-8497-d591984597ea.png)

**Comment by odysseus9672** [comment]
This sounds like it was a feature added to deluxetables after this style file was made. My suggestion: fork this distro, and start a thread on https://tex.stackexchange.com/ soliciting help, like I did. You could also try to dig in to the aastex style files to find a way to copy the new feature over. I wish I could offer more help, but I'm not a TeX expert. I make this available as is in the hopes others will find it useful.

Good luck!
